# Generated by Django 5.2.3 on 2025-08-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('userprofile', '0022_alter_userregistration_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='userprofile.userregistration'),
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
