# Generated by Django 5.2.3 on 2025-08-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_transaction_user_delete_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
