# Generated by Django 5.2.3 on 2025-08-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_initial'),
        ('userprofile', '0022_alter_userregistration_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userregistration'),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userregistration'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userregistration'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userregistration'),
        ),
    ]
