# Generated by Django 5.2.3 on 2025-08-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_chatmessage_user_alter_depositrequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='DepositRequest',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
