# Generated by Django 5.2.3 on 2025-08-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_initial'),
        ('userprofile', '0022_alter_userregistration_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='user',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='Processing', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('front_id_card', models.FileField(blank=True, null=True, upload_to='id_cards/front')),
                ('back_id_card', models.FileField(blank=True, null=True, upload_to='id_cards/back')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='userprofile.userregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='DepositRequest',
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
