# Generated by Django 5.2.3 on 2025-08-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_withdrawalrequest_user_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Declined', 'Declined'), ('Voided', 'Voided')], default='Processing', max_length=20),
        ),
    ]
