# Generated by Django 5.2.3 on 2025-08-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Declined', 'Declined&nbsp(Admin)'), ('Voided', 'Voided&nbsp(You)')], default='Processing', max_length=20),
        ),
    ]
