# Generated by Django 5.2.3 on 2025-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userregistration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_id',
            field=models.CharField(default='alpha_default_id', editable=False, max_length=20, unique=True),
        ),
    ]
