# Generated by Django 5.2.3 on 2025-06-17 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userregistration_balance_userregistration_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='alpha_default_id', editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('password', models.CharField(max_length=128)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Reg',
                'verbose_name_plural': 'User Regs',
            },
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
