# Generated by Django 5.2.3 on 2025-06-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userreg_delete_userregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReg',
        ),
    ]
