# Generated by Django 5.2.3 on 2025-06-18 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
