# Generated by Django 5.2.3 on 2025-06-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_userloginlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userregistration'),
        ),
    ]
