# Generated by Django 5.2.3 on 2025-06-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_trade_transaction_useraccount_delete_userloginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_registration',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_registration',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
