# Generated by Django 5.2.3 on 2025-06-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_remove_transaction_user_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Crypto'), ('stocks', 'Stocks'), ('commodities', 'Commodities')], max_length=20)),
                ('asset_name', models.CharField(max_length=50)),
                ('trade_type', models.CharField(choices=[('CALL', 'Call (Up)'), ('PUT', 'Put (Down)')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('opening_time', models.DateTimeField(auto_now_add=True)),
                ('closing_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=10)),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('PENDING', 'Pending'), ('DRAW', 'Draw')], default='PENDING', max_length=10)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='userprofile.userregistration')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-opening_time'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card'), ('Crypto (USDT)', 'Crypto (USDT)'), ('Crypto (BTC)', 'Crypto (BTC)'), ('Crypto (ETH)', 'Crypto (ETH)'), ('PayPal', 'PayPal')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('withdrawal_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('withdrawal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('front_id_path', models.CharField(blank=True, max_length=255, null=True)),
                ('back_id_path', models.CharField(blank=True, max_length=255, null=True)),
                ('user_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='userprofile.userregistration')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='userprofile.userregistration')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
            },
        ),
    ]
