# Generated by Django 5.2.3 on 2025-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_remove_transaction_user_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Crypto'), ('stocks', 'Stocks'), ('commodities', 'Commodities')], max_length=20)),
                ('asset', models.CharField(max_length=50)),
                ('trade_type', models.CharField(choices=[('Call', 'Call'), ('Put', 'Put')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry', models.IntegerField(help_text='Expiry in minutes')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Won', 'Won'), ('Lost', 'Lost')], default='Active', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
