# Generated by Django 5.2.3 on 2025-07-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0017_trade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
