# Generated by Django 5.2.3 on 2025-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
