# Generated by Django 5.2.3 on 2025-07-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_userregistration_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balance_updated',
            field=models.BooleanField(default=False),
        ),
    ]
