# Generated by Django 5.2.3 on 2025-07-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_trade_balance_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=12),
        ),
    ]
