# Generated by Django 5.2.3 on 2025-09-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_alter_userregistration_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='main_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
