# Generated by Django 5.2.3 on 2025-09-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_userregistration_main_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='main_id',
            field=models.CharField(default='TRD0000000000FX', editable=False, max_length=20, unique=True),
        ),
    ]
