# Generated by Django 5.2.3 on 2025-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0024_alter_userregistration_main_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='main_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
