# Generated by Django 5.2.3 on 2025-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0002_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'db_table': 'Stat',
                'managed': True,
            },
        ),
    ]
