# Generated by Django 5.2.3 on 2025-06-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0003_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=90)),
                ('text', models.TextField()),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
                ('title3', models.CharField(max_length=50)),
                ('title4', models.CharField(max_length=50)),
                ('title5', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'db_table': 'Education',
                'managed': True,
            },
        ),
    ]
