# Generated by Django 5.2.3 on 2025-06-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0004_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
