# Generated by Django 5.2.3 on 2025-12-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0005_alter_education_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='terms',
            field=models.FileField(blank=True, null=True, upload_to='doc'),
        ),
    ]
