# Generated by Django 5.2.3 on 2025-12-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0006_companyprofile_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='BROKERS')),
                ('facebook_link', models.CharField(max_length=150)),
                ('instagram_link', models.CharField(max_length=150)),
                ('telegram_link', models.CharField(max_length=150)),
                ('about', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'broker',
                'verbose_name_plural': 'brokers',
                'db_table': 'Broker',
                'managed': True,
            },
        ),
    ]
