# Generated by Django 5.2.3 on 2025-12-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0007_brokers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='telegram',
            field=models.CharField(blank=True, default='ab', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='whatsapp',
            field=models.CharField(blank=True, default='ab', max_length=150, null=True),
        ),
    ]
