# Generated by Django 5.2.3 on 2025-12-29 18:04

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary', '0008_companyprofile_telegram_companyprofile_whatsapp'),
        ('userprofile', '0025_alter_userregistration_main_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 12, 29, 19, 4, 27, 93001, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userregistration')),
            ],
        ),
    ]
